Remove redundant sh quoting

diff --git a/bin/distlinks b/bin/distlinks
--- a/bin/distlinks
+++ b/bin/distlinks
@@ -1,19 +1,19 @@
 #!/usr/bin/env sh
 
 Echo() {
-	printf '%s\n' "${*}"
+	printf '%s\n' "$*"
 }
 
 Message() {
-	Echo "${0##*/}: ${*}" >&2
+	Echo "${0##*/}: $*" >&2
 }
 
 Warning() {
-	Message "warning: ${*}"
+	Message "warning: $*"
 }
 
 Fatal() {
-	Message "fatal: ${*}"
+	Message "fatal: $*"
 	exit 1
 }
 
@@ -24,59 +24,59 @@ else	distdir=`portageq distdir 2>/dev/null` \
 	|| Fatal 'portageq distdir failed'
 fi
 # Add a paranoid sanity check:
-case ${distdir} in
-/*/*)	test -d "${distdir}";;
+case $distdir in
+/*/*)	test -d "$distdir";;
 *)	false;;
 esac || Fatal 'cannot determine DISTDIR appropriate for this script'
 
 obsdir='.obsolete'
 saveprefix='.save'
-save="${saveprefix}."
+save=$saveprefix.
 
 maindir=${distdir%/*}
 distfiles=${distdir##*/}
 
 Usage() {
 	Echo "Usage: ${0##*/} [options] [create|remove|help]
-For each directory in ${maindir}/* (except: ${distfiles} empty fetch)
-create (remove) corresponding dirs ${distdir}/${save}*,
+For each directory in $maindir/* (except: $distfiles empty fetch)
+create (remove) corresponding dirs $distdir/$save*,
 creating (removing) corresponding symbolic links in these directories;
 all permissions and ownerships are set appropriately, and the directories
 are flattened. If reasonable, the empty directory
-${maindir}/empty
+$maindir/empty
 is created (removed).
 
-Also a cleanup is made: Links in ${distdir}
-or in its ${obsdir}/${save}* subdirectories are deleted if they point to
-nonexisting files. Also empty ${save}* directories are removed.
+Also a cleanup is made: Links in $distdir
+or in its $obsdir/$save* subdirectories are deleted if they point to
+nonexisting files. Also empty $save* directories are removed.
 Without option -R, also certain links are removed from
-${distdir} or ${distdir}/${obsdir}
+$distdir or $distdir/$obsdir
 (see option -r for more details).
 
-Finally, symlinks to ${distdir}/.restricted are created with
-trickyfetch ''  ${distdir} ''
+Finally, symlinks to $distdir/.restricted are created with
+trickyfetch ''  $distdir ''
 
 The following options are available:
--1 Flattened structure: Do not use ${save}* subdirectories but directly
-   create the links in ${distdir}
+-1 Flattened structure: Do not use $save* subdirectories but directly
+   create the links in $distdir
    In addition, create there links pointing to those files in
-   ${obsdir} or ${saveprefix}* which are not created by this script
-   (the ${obsdir}/*-src directories are moved out if possible).
+   $obsdir or $saveprefix* which are not created by this script
+   (the $obsdir/*-src directories are moved out if possible).
    This has the advantage that the getdelta script will find all your
    old versions afterwards (unfortunately, this script is not looking
    into subdirectories of $distdir).
--f Force flattening: As -1, but flatten ${obsdir} not by creating links
-   but by moving all its content into ${distdir}
+-f Force flattening: As -1, but flatten $obsdir not by creating links
+   but by moving all its content into $distdir
 -r This option is the default: Remove always corresponding links in
-   ${distdir} and in ${distdir}/${obsdir}
-   Also remove links in ${distdir}
-   which point to files in ${obsdir} or ${saveprefix}*
+   $distdir and in $distdir/$obsdir
+   Also remove links in $distdir
+   which point to files in $obsdir or $saveprefix*
 -R Avoid using -r
 -k Keep all links/dirs which already exist
--C No cleanup (do not remove nonexisiting links or empty ${save}* dirs)
+-C No cleanup (do not remove nonexisiting links or empty $save* dirs)
 -a Create all links, even if corresponding links exist in
-	${distdir}
-or in its ${obsdir} subdirectory
+	$distdir
+or in its $obsdir subdirectory
 -T Omit execution of the trickyfetch script at the end
 -v Be verbose
 -O Do not attempt to make portage the owner of directories"
@@ -94,7 +94,7 @@ chowner=:
 tricky=:
 OPTIND=1
 while getopts '1farRcCkvOThH?' opt
-do	case ${opt} in
+do	case $opt in
 	1)	flatten=:
 		forceflatten=false;;
 	f)	flatten=:
@@ -111,7 +111,7 @@ do	case ${opt} in
 	*)	Usage 0;;
 	esac
 done
-shift $(( ${OPTIND} - 1 ))
+shift $(( $OPTIND - 1 ))
 
 case ${1:-create} in
 [cC]*)
@@ -124,250 +124,250 @@ case ${1:-create} in
 	Usage;;
 esac
 
-if ${quiet}
+if $quiet
 then	Info() {
 	:
 }
 else	Info() {
-	Echo "${*}"
+	Echo "$*"
 }
 fi
 
 which=`command -v which` || which=
 MakeExternal() {
-	[ "${which}" = 'which' ] && eval ${1}=\`which ${2}\` \
-		|| eval ${1}=\`command -v ${2}\` || eval ${1}=
-	eval ": \${${1}:=${2}}"
+	[ "$which" = 'which' ] && eval $1=\`which $2\` \
+		|| eval $1=\`command -v $2\` || eval $1=
+	eval ": \${$1:=$2}"
 }
 
 OptExternal() {
-	eval "[ -n \"\${${1}:++}\" ]" || MakeExternal ${1} ${2-${1}}
+	eval "[ -n \"\${$1:++}\" ]" || MakeExternal $1 ${2-$1}
 }
 
 
 Cd() {
-	case ${1} in
-	/*)	cd "${1}" >/dev/null 2>&1 || Fatal "cannot cd to ${1}";;
-	*)	cd "./${1#./}" >/dev/null 2>&1 || Fatal "cannot cd to ${PWD}/${1#./}"
+	case $1 in
+	/*)	cd "$1" >/dev/null 2>&1 || Fatal "cannot cd to $1";;
+	*)	cd "./${1#./}" >/dev/null 2>&1 || Fatal "cannot cd to $PWD/${1#./}"
 	esac
 }
 
 IsInCut() {
-	case ${1} in
-	"${distfiles}"|empty|fetch)	return 0;;
+	case $1 in
+	"$distfiles"|empty|fetch)	return 0;;
 	esac
 	return 1
 }
 
 chowner_mode=
 Chowner() {
-	[ -n "${chowner_mode:++}" ] && return ${chowner_mode}
-	if ${chowner}
+	[ -n "${chowner_mode:++}" ] && return $chowner_mode
+	if $chowner
 	then	[ -n "${UID:++}" ] || UID=`id -u`
-		[ "${UID}" -eq 0 ] || chowner=false
+		[ "$UID" -eq 0 ] || chowner=false
 	fi
-	${chowner}
-	chowner_mode=${?}
-	return ${chowner_mode}
+	$chowner
+	chowner_mode=$?
+	return $chowner_mode
 }
 
 Ownership() {
 	if Chowner
-	then	chown ${2} -- 'portage:portage' "${1}" || \
-			Warning "cannot change ownership of ${1}"
-	else	chgrp ${2} -- 'portage' "${1}" || \
-			Warning "cannot change group of ${1}"
+	then	chown $2 -- 'portage:portage' "$1" || \
+			Warning "cannot change ownership of $1"
+	else	chgrp $2 -- 'portage' "$1" || \
+			Warning "cannot change group of $1"
 	fi
 }
 
 MkDir() {
-	test -d "${1}" && return
-	Info "mkdir ${1}"
-	if mkdir -m 2775 -- "${1}"
-	then	Ownership "${1}"
-	else	Warning "cannot mkdir ${1}"
+	test -d "$1" && return
+	Info "mkdir $1"
+	if mkdir -m 2775 -- "$1"
+	then	Ownership "$1"
+	else	Warning "cannot mkdir $1"
 	fi
 }
 
 RmLink() {
 	for rmln
-	do	test -h "${rmln}" || continue
-		Info "removing ${rmln}"
-		rm -- "${rmln}" || Warning "cannot remove ${rmln}"
+	do	test -h "$rmln" || continue
+		Info "removing $rmln"
+		rm -- "$rmln" || Warning "cannot remove $rmln"
 	done
 }
 
 RmDir() {
 	for rmdiri in \
-		"${1}/"* \
-		"${1}/".*
+		"$1/"* \
+		"$1/".*
 	do	case ${rmdiri##*/} in
 		.|..)	continue;;
 		esac
-		test -e "${rmdiri}" && return
+		test -e "$rmdiri" && return
 	done
-	if rmdir -- "${1}" >/dev/null 2>&1
-	then	Info "rmdir ${1}"
-	else	Warning "cannot rmdir ${1}"
+	if rmdir -- "$1" >/dev/null 2>&1
+	then	Info "rmdir $1"
+	else	Warning "cannot rmdir $1"
 	fi
 }
 
 RmLinkDir() {
-	test -d "${1}" || return 0
-	RmLink "${1}"/*
-	RmDir "${1}"
+	test -d "$1" || return 0
+	RmLink "$1"/*
+	RmDir "$1"
 }
 
 CreateLink() {
-	Info "creating link: ${3}${2} -> ${1}"
-	if ln -sn -- "${1}" "${2}"
-	then	Ownership "${2}" -h
-	else	Warning "cannot create link ${3}${2}"
+	Info "creating link: $3$2 -> $1"
+	if ln -sn -- "$1" "$2"
+	then	Ownership "$2" -h
+	else	Warning "cannot create link $3$2"
 	fi
 }
 
 Mv() {
-	Info "moving: ${1} -> ${2}"
-	mv -- "${1}" "${2}" || Warning "cannot move ${1} -> ${2}"
+	Info "moving: $1 -> $2"
+	mv -- "$1" "$2" || Warning "cannot move $1 -> $2"
 }
 
 CreateFiles() {
-	test -f "${1}" || return
+	test -f "$1" || return
 	crshort=${1##*/}
-	test -r "${crshort}" && return
-	if ! ${all}
-	then	if test -r "${distdir}/${crshort}" || \
-			test -r "${distdir}/${obsdir}/${crshort}"
+	test -r "$crshort" && return
+	if ! $all
+	then	if test -r "$distdir/$crshort" || \
+			test -r "$distdir/$obsdir/$crshort"
 		then	return
 		fi
 	fi
-	CreateLink "${1}" "${crshort}" "${2}"
+	CreateLink "$1" "$crshort" "$2"
 }
 
 RemoveFiles() {
-	test -f "${1}" || return
+	test -f "$1" || return
 	rmshort=${1##*/}
-	RmLink "${rmshort}" "${distdir}/${obsdir}/${rmshort}"
+	RmLink "$rmshort" "$distdir/$obsdir/$rmshort"
 }
 
 find=
 Action() {
 	acdir=
 	acexit='exit 0'
-	${deldist} || [ "${1}" = 'CreateFiles' ] && acexit=:
-	Cd "${maindir}"
-	if ${remove} && [ "${1}" = 'RemoveFiles' ]
+	$deldist || [ "$1" = 'CreateFiles' ] && acexit=:
+	Cd "$maindir"
+	if $remove && [ "$1" = 'RemoveFiles' ]
 	then	test -d 'empty' && RmDir 'empty'
 	else	MkDir 'empty'
 	fi
 	for acfile in *
-	do	IsInCut "${acfile}" && continue
-		test -r "${acfile}" || continue
+	do	IsInCut "$acfile" && continue
+		test -r "$acfile" || continue
 		(
-			Cd "${distdir}"
-			if [ "${1}" = 'RemoveFiles' ]
-			then	RmLinkDir "${save}${acfile}"
-			elif ! ${flatten}
-			then	MkDir "${save}${acfile}"
-				Cd "${save}${acfile}"
-				acdir="${save}${acfile}/"
+			Cd "$distdir"
+			if [ "$1" = 'RemoveFiles' ]
+			then	RmLinkDir "$save$acfile"
+			elif ! $flatten
+			then	MkDir "$save$acfile"
+				Cd "$save$acfile"
+				acdir=$save$acfile/
 			fi
-			${acexit}
-			for acsub in "${maindir}/${acfile}"/*
-			do	if test -d "${acsub}"
+			$acexit
+			for acsub in "$maindir/$acfile"/*
+			do	if test -d "$acsub"
 				then	OptExternal find
-					"${find}" -L "${acsub}" -print | while read -r fil
-					do	"${1}" "${fil}" "${acdir}"
+					"$find" -L "$acsub" -print | while read -r fil
+					do	"$1" "$fil" "$acdir"
 					done
-				else	test -r "${acsub}" || continue
-					"${1}" "${acsub}" "${acdir}"
+				else	test -r "$acsub" || continue
+					"$1" "$acsub" "$acdir"
 				fi
 			done
 			:
-		) || exit ${?}
+		) || exit $?
 	done
 	return 0
 }
 
 RmBadLinks() {
 	for rmbadl in * .*
-	do	test -h "${rmbadl}" && ! test -r "${rmbadl}" \
-			&& RmLink "${rmbadl}"
+	do	test -h "$rmbadl" && ! test -r "$rmbadl" \
+			&& RmLink "$rmbadl"
 	done
 }
 
 Cleanup() {
-	Cd "${distdir}"
+	Cd "$distdir"
 	RmBadLinks
-	for clns in "${obsdir}" "${save}"*
-	do	test -d "${clns}" || continue
+	for clns in "$obsdir" "$save"*
+	do	test -d "$clns" || continue
 		(
-			Cd "${clns}" && RmBadLinks
+			Cd "$clns" && RmBadLinks
 		)
-		[ -n "${1:++}" ] && [ "${clns}" != "${obsdir}" ] && RmDir "${clns}"
+		[ -n "${1:++}" ] && [ "$clns" != "$obsdir" ] && RmDir "$clns"
 	done
 }
 
 LinkToSave() {
-	Cd "${distdir}"
+	Cd "$distdir"
 	for lnsavi in \
-		"${saveprefix}"*/* \
-		"${saveprefix}"*/.*
+		"$saveprefix"*/* \
+		"$saveprefix"*/.*
 	do	lnsavs=${lnsavi##*/}
-		test -r "${lnsavs}" || CreateLink "${lnsavi}" "${lnsavs}"
+		test -r "$lnsavs" || CreateLink "$lnsavi" "$lnsavs"
 	done
 }
 
 FlattenObsolete() {
-	Cd "${distdir}"
-	for flobs in "${obsdir}"/* "${obsdir}"/.*
-	do	test -r "${flobs}" || continue
-		test -d "${flobs}" && continue
+	Cd "$distdir"
+	for flobs in "$obsdir"/* "$obsdir"/.*
+	do	test -r "$flobs" || continue
+		test -d "$flobs" && continue
 		flobssht=${flobs##*/}
-		test -r "${flobssht}" && continue
-		if ${forceflatten}
-		then	Mv "${flobs}" "${flobssht}"
-		else	CreateLink "${flobs}" "${flobssht}"
+		test -r "$flobssht" && continue
+		if $forceflatten
+		then	Mv "$flobs" "$flobssht"
+		else	CreateLink "$flobs" "$flobssht"
 		fi
 	done
 }
 
 RemoveSavelinks() {
-	Cd "${distdir}"
+	Cd "$distdir"
 	for rmobs in \
-		"${obsdir}"/* \
-		"${obsdir}"/.* \
-		"${saveprefix}"*/* \
-		"${saveprefix}"*/.*
+		"$obsdir"/* \
+		"$obsdir"/.* \
+		"$saveprefix"*/* \
+		"$saveprefix"*/.*
 	do	RmLink "${rmobs##*/}"
 	done
 }
 
 Trickyfetch() {
-	Info "Finishing with trickyfetch '' ${distdir} ''"
-	trickyfetch '' "${distdir}" '' >/dev/null
+	Info "Finishing with trickyfetch '' $distdir ''"
+	trickyfetch '' "$distdir" '' >/dev/null
 }
 
-if ${cleanup}
+if $cleanup
 then	Cleanup
 fi
-if ! ${keep}
+if ! $keep
 then	Action RemoveFiles
 fi
-if ${deldist} && ! ${keep}
+if $deldist && ! $keep
 then	RemoveSavelinks
 fi
-if ${flatten}
+if $flatten
 then	LinkToSave
 	FlattenObsolete
 fi
-if ! ${remove}
+if ! $remove
 then	Action CreateFiles
 fi
-if ${cleanup}
+if $cleanup
 then	Cleanup dirs
 fi
-if ${tricky}
+if $tricky
 then	Trickyfetch
 fi
 :
diff --git a/bin/obsolete b/bin/obsolete
--- a/bin/obsolete
+++ b/bin/obsolete
@@ -1,25 +1,25 @@
 #!/usr/bin/env sh
 
 Echo() {
-	printf '%s\n' "${*}"
+	printf '%s\n' "$*"
 }
 
 Fatal() {
-	Echo "${0##*/}: ${1}" >&2
+	Echo "${0##*/}: $1" >&2
 	exit ${2:-1}
 }
 
 Warn() {
-	Echo "${0##*/}: warning: ${1}" >&2
+	Echo "${0##*/}: warning: $1" >&2
 }
 
 Info() {
-	Echo "# ${*}"
+	Echo "# $*"
 }
 
 Exec() {
-	Info "${*}"
-	"${@}" || Fatal "${*} failed" ${?}
+	Info "$*"
+	"$@" || Fatal "$* failed" $?
 }
 
 if command -v eix-functions.sh >/dev/null 2>&1
@@ -27,30 +27,30 @@ then	. eix-functions.sh
 	ReadVar distdir DISTDIR
 else	distdir=`portageq distdir` || distdir=
 fi
-case ${distdir} in
-/*)	test -d "${distdir}";;
+case $distdir in
+/*)	test -d "$distdir";;
 *)	false;;
 esac || Fatal 'cannot determine DISTDIR'
 
-Exec cd -- "${distdir}"
+Exec cd -- "$distdir"
 if ! test -d '.obsolete'
-then	Exec mkdir -m 2775 .obsolete || exit ${?}
+then	Exec mkdir -m 2775 .obsolete || exit $?
 	[ -n "${UID:++}" ] || UID=`id -u`
-	if [ "${UID}" -eq 0 ]
+	if [ "$UID" -eq 0 ]
 	then	Exec chown 'portage:portage' '.obsolete'
 	else	Exec chgrp 'portage' '.obsolete'
 	fi
 fi
 Info 'mv -- * .obsolete'
 for i in *
-do	if test -r "${i}" && ! test -d "${i}" && ! test -r ".obsolete/${i}"
-	then	mv -- "${i}" .obsolete || Fatal "mv ${i} .obsolete failed"
-	elif [ "${i}" != '*' ]
-	then	Warn "not moving to .obsolete: ${i}"
+do	if test -r "$i" && ! test -d "$i" && ! test -r ".obsolete/$i"
+	then	mv -- "$i" .obsolete || Fatal "mv $i .obsolete failed"
+	elif [ "$i" != '*' ]
+	then	Warn "not moving to .obsolete: $i"
 	fi
 done
 PORTAGE_CHECKSUM_FILTER='-* size'
-Info "export PORTAGE_CHECKSUM_FILTER='${PORTAGE_CHECKSUM_FILTER}'"
+Info "export PORTAGE_CHECKSUM_FILTER='$PORTAGE_CHECKSUM_FILTER'"
 export PORTAGE_CHECKSUM_FILTER
 Info 'emerge -feD --with-bdeps=y @system @world'
 exec emerge -feD --with-bdeps=y '@system' '@world'
diff --git a/bin/trickyfetch b/bin/trickyfetch
--- a/bin/trickyfetch
+++ b/bin/trickyfetch
@@ -8,95 +8,95 @@ WGET=
 
 # Source the configfile, looking for it first in /etc then in $PATH.
 # By POSIX, the shell exits if this file does not exist
-PATH="/etc${PATH:+:}${PATH}" . trickyfetch.conf
+PATH=/etc${PATH:+:}$PATH . trickyfetch.conf
 
 export URI DISTDIR FILE
-URI=${1}
-DISTDIR=${2}
-FILE=${3}
+URI=$1
+DISTDIR=$2
+FILE=$3
 
 Echo() {
-	printf '%s\n' "${*}"
+	printf '%s\n' "$*"
 }
 
 case ${NOCOLOR:-false} in
 [fFnN0]*|[oO][fF]*)
 Info() {
-	printf '\033[1;35m>>> %s\033[0m: \033[1;32m%s\033[0m\n' "${0##*/}" "${*}"
+	printf '\033[1;35m>>> %s\033[0m: \033[1;32m%s\033[0m\n' "${0##*/}" "$*"
 };;
 *)
 Info() {
-	Echo ">>> ${0##*/}: ${*}"
+	Echo ">>> ${0##*/}: $*"
 };;
 esac
 
 Error() {
-	Echo "${0##*/}: ${*}" >&2
-	${LOGGING_ERROR:-:} "${*}"
+	Echo "${0##*/}: $*" >&2
+	${LOGGING_ERROR:-:} "$*"
 }
 
 Fatal() {
-	Error "fatal: ${*}"
+	Error "fatal: $*"
 	exit 1
 }
 
-if [ -z "${DISTDIR:++}" ] || ! test -d "${DISTDIR}"
+if [ -z "${DISTDIR:++}" ] || ! test -d "$DISTDIR"
 then	Info 'Called with wrong arguments'
-	Fatal "second argument \"${DISTDIR}\" is not a directory"
+	Fatal "second argument \"$DISTDIR\" is not a directory"
 fi
 
 # First argument must be one of
 #  Info  Verbose
 #  :     Non-verbose
-# The other arguments are candidates for files/dirs to be moved to ${DISTDIR}.
+# The other arguments are candidates for files/dirs to be moved to $DISTDIR.
 # Success if at least one file/dir could be moved.
 
 Mv() {
 	# If mv_cont is continue, no (further) dir-tricky_contents
 	#  are moved to avoid mixing dirs
 	mv_cont=
-	mv_info=${1}
+	mv_info=$1
 	shift
 	for mv_i
-	do	test -e "${mv_i}" || continue
-		mv_dest="${DISTDIR}/${mv_i##*/}"
-		if ! test -e "${mv_dest}"
-		then	${mv_info} "Moving source from ${mv_i}"
-			mv -- "${mv_i}" "${mv_dest}" && return 0
+	do	test -e "$mv_i" || continue
+		mv_dest=$DISTDIR/${mv_i##*/}
+		if ! test -e "$mv_dest"
+		then	$mv_info "Moving source from $mv_i"
+			mv -- "$mv_i" "$mv_dest" && return 0
 			mv_cont=continue
-			Error "failed moving ${mv_i}"
+			Error "failed moving $mv_i"
 			continue
 		fi
-		${mv_cont}
-		test -d "${mv_dest}" || continue
-		test -d "${mv_i}" || continue
-		${mv_info} "Moving dir-content of ${mv_i}/*"
+		$mv_cont
+		test -d "$mv_dest" || continue
+		test -d "$mv_i" || continue
+		$mv_info "Moving dir-content of $mv_i/*"
 		mv_match=:
-		for mv_j in "${mv_i}"/*
+		for mv_j in "$mv_i"/*
 		do	mv_name=${mv_j##*/}
-			case ${mv_name} in
+			case $mv_name in
 			.|..)	continue;;
 			esac
-			test -e "${mv_j}" || continue
-			if test -e "${mv_dest}/${mv_name}"
+			test -e "$mv_j" || continue
+			if test -e "$mv_dest/$mv_name"
 			then	mv_match=false
 				continue
 			fi
-			mv -- "${mv_j}" "${mv_dest}" || mv_match=false
+			mv -- "$mv_j" "$mv_dest" || mv_match=false
 		done
-		if ${mv_match} && test -L "${mv_i}"
-		then	rm -- "${mv_i}" && return
-		else	rmdir -- "${mv_i}" && return
+		if $mv_match && test -L "$mv_i"
+		then	rm -- "$mv_i" && return
+		else	rmdir -- "$mv_i" && return
 		fi
 		mv_cont=continue
-		Error "failed moving dir-content of ${mv_i}/*"
+		Error "failed moving dir-content of $mv_i/*"
 	done
 	return 1
 }
 
 # These tasks are alway done, even if no file should need to be fetched:
 
-# A somewhat special treatment is needed for ${DISTDIR}/*-src, because the
+# A somewhat special treatment is needed for $DISTDIR/*-src, because the
 # files in these directories are not fetched by
 # "emerge -feD --with-bdeps y @world @system".
 # Therefore, trickyfetch tacitly moves back these directories from .obsolete
@@ -107,18 +107,18 @@ Mv() {
 # has a reason if he moves some *-src there, so trickyfetch should better
 # not interfere.
 
-for i in "${DISTDIR}/.obsolete"/*-src
-do	test -d "${i}" && Mv : "${i}"
+for i in "$DISTDIR/.obsolete"/*-src
+do	test -d "$i" && Mv : "$i"
 done
 
 # The files in .restricted are always linked if they don't exist
 
-for i in "${DISTDIR}/.restricted"/*
-do	test -e "${i}" || continue
+for i in "$DISTDIR/.restricted"/*
+do	test -e "$i" || continue
 	name=${i##*/}
-	Mv : "${DISTDIR}/.obsolete/${name}" "${DISTDIR}"/.save*/"${name}" \
-		|| test -e "${DISTDIR}/${name}" \
-		|| ln -s -- "${i}" "${DISTDIR}/${name}"
+	Mv : "$DISTDIR/.obsolete/$name" "$DISTDIR"/.save*/"$name" \
+		|| test -e "$DISTDIR/$name" \
+		|| ln -s -- "$i" "$DISTDIR/$name"
 done
 
 # An empty filename is something which we assume is already downloaded
@@ -128,27 +128,27 @@ done
 # Now trickyfetch moves the files if possible
 # Finish if at least one move was successful
 
-Mv Info "${DISTDIR}/.obsolete/${FILE}" "${DISTDIR}"/.save*/"${FILE}" && exit
+Mv Info "$DISTDIR/.obsolete/$FILE" "$DISTDIR"/.save*/"$FILE" && exit
 
 # Now we log, since we really have to fetch something and not only to move:
 
-if [ -n "${LOGGING_FETCH}" ]
-then	if [ "${URI##*/}" = "${FILE}" ]
-	then	${LOGGING_FETCH} "${URI}"
-	else	${LOGGING_FETCH} "${URI}" "${FILE}"
+if [ -n "$LOGGING_FETCH" ]
+then	if [ "${URI##*/}" = "$FILE" ]
+	then	$LOGGING_FETCH "$URI"
+	else	$LOGGING_FETCH "$URI" "$FILE"
 	fi
 fi
 
 # If LOCALFETCHCOMMAND exists, use it:
 
 if [ -n "${LOCALFETCHCOMMAND:++}" ]
-then	Info "Using \${LOCALFETCHCOMMAND} for ${URI}"
-	eval "${LOCALFETCHCOMMAND}"
+then	Info "Using \$LOCALFETCHCOMMAND for $URI"
+	eval "$LOCALFETCHCOMMAND"
 	exit
 fi
 
 # /* Optional getdelta support
-if [ -n "${TRICKYFETCH_GETDELTA}" ]
+if [ -n "$TRICKYFETCH_GETDELTA" ]
 then
 
 ReadMirror() {
@@ -163,9 +163,9 @@ ReadMirror() {
 GoodDeltaMirror() {
 	ReadMirror
 	retmirror=0
-	for mirror in ${GENTOO_MIRRORS}
-	do	case ${URI} in
-		*"${mirror#*://}"*)	return ${retmirror};;
+	for mirror in $GENTOO_MIRRORS
+	do	case $URI in
+		*"${mirror#*://}"*)	return $retmirror;;
 		esac
 		retmirror=1
 	done
@@ -173,33 +173,33 @@ GoodDeltaMirror() {
 
 IsAMatch() {
 	for isamask
-	do	case ${FILE} in
-		${isamask})	return 0;;
+	do	case $FILE in
+		$isamask)	return 0;;
 		esac
 	done
 	return 1
 }
 
 DeltaExcluded() {
-	[ -n "${DELTA_EXCLUDE:++}" ] && IsAMatch `find -L "${DELTA_EXCLUDE}" \
+	[ -n "${DELTA_EXCLUDE:++}" ] && IsAMatch `find -L "$DELTA_EXCLUDE" \
 		'(' '(' -name '.*' -o -name '*~' ')' -prune ')' -o \
 		-type f -exec cat '{}' '+'`
 }
 
 set -f
-if IsAMatch ${NODELTA}
-then	Info 'Not using getdelta since ${NODELTA} matches the filename'
+if IsAMatch $NODELTA
+then	Info 'Not using getdelta since $NODELTA matches the filename'
 elif ! command -v getdelta.sh >/dev/null 2>&1
 then	Info 'Not using app-portage/getdelta since it is not installed'
-elif test -e "${DISTDIR}/.nodelta"
-then	Info 'Not using getdelta since ${DISTDIR}/.nodelta exists'
+elif test -e "$DISTDIR/.nodelta"
+then	Info 'Not using getdelta since $DISTDIR/.nodelta exists'
 elif ! GoodDeltaMirror
 then	Info 'Not using getdelta since we are on a later GENTOO_MIRROR'
 elif DeltaExcluded
-then	Info 'Not using getdelta since filename matches in ${DELTA_EXCLUDE}'
-else	Info "Calling getdelta to fetch ${FILE}"
-	exec getdelta.sh "${URI}" "${FILE}"
-	Fatal "could not execute getdelta.sh for ${FILE}"
+then	Info 'Not using getdelta since filename matches in $DELTA_EXCLUDE'
+else	Info "Calling getdelta to fetch $FILE"
+	exec getdelta.sh "$URI" "$FILE"
+	Fatal "could not execute getdelta.sh for $FILE"
 fi
 
 fi
@@ -207,14 +207,14 @@ fi
 
 # The default wget is actually only the final fallback:
 
-: ${WGET:=wget -t 1 -T 15 --passive-ftp --no-glob ${WGET_EXTRA_OPTS}}
-if [ "${URI##*/}" = "${FILE}" ]
-then	Info "Calling wget to fetch ${FILE}"
-	eval ${WGET} -P \"\${DISTDIR}\" ${WGET_EXTRA_OPTS} -- \"\${URI}\"
-else	Info "Calling wget -O ${FILE}"
-	eval ${WGET} -O \"\${DISTDIR}/\${FILE}\" ${WGET_EXTRA_OPTS} -- \"\${URI}\"
+: ${WGET:=wget -t 1 -T 15 --passive-ftp --no-glob $WGET_EXTRA_OPTS}
+if [ "${URI##*/}" = "$FILE" ]
+then	Info "Calling wget to fetch $FILE"
+	eval $WGET -P \"\$DISTDIR\" $WGET_EXTRA_OPTS -- \"\$URI\"
+else	Info "Calling wget -O $FILE"
+	eval $WGET -O \"\$DISTDIR/\$FILE\" $WGET_EXTRA_OPTS -- \"\$URI\"
 fi && exit 0
-Error '$WGET for '"${FILE} failed."
+Error '$WGET for '"$FILE failed."
 Error 'In some cases, it might help to set $WGET_EXTRA_OPTS appropriately,'
 Error 'for instance (if you are willing to take the security risk):'
 Error '	export WGET_EXTRA_OPTS=--no-check-certificate'
