Simplify quoting

diff --git a/bin/obsolete b/bin/obsolete
--- a/bin/obsolete
+++ b/bin/obsolete
@@ -1,16 +1,20 @@
 #! /usr/bin/env sh
 
+Echo() {
+	printf '%s\n' "${*}"
+}
+
 Fatal() {
-	printf '%s\n' "${0##*/}: ${1}" >&2
+	Echo "${0##*/}: ${1}" >&2
 	exit ${2:-1}
 }
 
 Warn() {
-	printf '%s\n' "${0##*/}: warning: ${1}" >&2
+	Echo "${0##*/}: warning: ${1}" >&2
 }
 
 Info() {
-	printf '# %s\n' "${*}"
+	Echo "# ${*}"
 }
 
 Exec() {
@@ -18,20 +22,19 @@ Exec() {
 	"${@}" || Fatal "${*} failed" ${?}
 }
 
-eix_functions=`command -v eix-functions.sh 2>/dev/null` || eix_functions=''
+eix_functions=`command -v eix-functions.sh 2>/dev/null` || eix_functions=
 if [ -n "${eix_functions}" ]
 then	. "${eix_functions}"
 	ReadVar distdir DISTDIR
-else	distdir=`portageq distdir` || distdir=''
+else	distdir=`portageq distdir` || distdir=
 fi
 case ${distdir} in
-/*)	test -d "${distdir}" || distdir='';;
-*)	distdir='';;
-esac
-[ -n "${distdir}" ] || Fatal 'cannot determine DISTDIR'
+/*)	test -d "${distdir}";;
+*)	false;;
+esac || Fatal 'cannot determine DISTDIR'
 
-Exec cd "${distdir}"
-if ! test -d ".obsolete"
+Exec cd -- "${distdir}"
+if ! test -d '.obsolete'
 then	( umask 002 && Exec mkdir .obsolete ) || exit ${?}
 	[ -n "${UID}" ] || UID=`id -u`
 	if [ "${UID}" -eq 0 ]
@@ -48,4 +51,4 @@ do	if test -r "${i}" && ! test -d "${i}" && ! test -r ".obsolete/${i}"
 	fi
 done
 Info 'emerge -feD --with-bdeps=y @system @world'
-exec emerge -feD --with-bdeps=y @system @world
+exec emerge -feD --with-bdeps=y '@system' '@world'
